theme: jekyll-theme-hacker
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
baseurl: /cryptol-course
plugins:
  - jekyll-relative-links
