name: Cryptol-Remote-API Template

on:
  workflow_call:
    inputs:
      ci_script_name:
        required: true
        type: string

env:
  CRYPTOL_SERVER_URL: http://0.0.0.0:8080

jobs:
  cryptol_job_template:
    runs-on: ubuntu-latest
    services:
      cryptol-remote-api:
        image: ghcr.io/galoisinc/cryptol-remote-api:2.13.0
        ports:
          - 8080:8080
        options: -v ${{ github.workspace }}:/home/cryptol
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Instal Cryptol Client
        run: pip install cryptol
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${PYTHONPATH}:${PWD}/.ci" >> $GITHUB_ENV
      - name: Run Cryptol CI Scripts
        run: for f in `find . -name ${{ inputs.ci_script_name }}`; do python $f; done

